---

- name: create exporter configuration file
  template:
    src: exporter-cfg.j2
    dest: "{{ script_exporter_dirs.config_dir }}/{{ script_exporter_config_file }}"
    owner: root
    group: "{{ script_exporter_user_name }}"
    mode: 0640
  notify: restart script_exporter service

- name: prepare sudoers file
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/script_exporter
    owner: root
    group: root
    mode: 0600
